INSERT INTO public.lens_catalog (code, name, lens_type, material, lens_index, power_range, price, warranty, engraving) VALUES
('SV-1', 'Bonthus Anti-Glare', 'single_vision', 'standard', '1.5', '-6 / -2', 0.0, 'NO Warranty', 'NO'),
('SV-2', 'Bonthus Blu Screen', 'single_vision', 'standard', '1.56', '- 6 / - 4 , - 8 / - 2   &   + 3 / + 1 , + 3.75 / - 4', 800.0, '6 Months Warranty Only For Coating Peel Off', 'NO'),
('SV-3', 'Bonthus Blu +', 'single_vision', 'standard', '1.56', '- 6 / - 4 , - 8 / - 2   &   + 3 / + 1 , + 3.75 / - 4', 1999.0, '6 Months Warrnty Only For Coating Peel Off', 'NO'),
('SV-4', 'Bonthus Night Driving Lens', 'single_vision', 'standard', '1.56', '- 6 / - 4 , - 8 / - 2   &   + 3 / + 1 , + 3.75 / - 4', 2499.0, '1 Year Warranty Only For Coating Peel Off', 'NO'),
('SV-5', 'Bonthus Blu Screen Len', 'single_vision', 'standard', '1.67', '-10 / - 4', 2999.0, '6 Months Warranty Only For Coating Peel Off', 'NO'),
('SV-6', 'Bonthus Blu +', 'single_vision', 'standard', '1.67', '-10 / - 4', 3999.0, '6 Months Warranty Only For Coating Peel Off', 'NO'),
('SV-7', 'Bonthus Night Driving Lens', 'single_vision', 'standard', '1.67', '-10 / - 4', 4499.0, '1 Year Warranty Only For Coating Peel Off', 'NO'),
('SV-8', 'Bonthus High Ultra Thin 1', 'single_vision', 'standard', '1.74', '- 20 / - 4', 6999.0, '1 Year Warranty Only For Coating Peel Off', 'NO'),
('SV-9', 'Bonthus High Ultra Thin 2', 'single_vision', 'standard', '1.74', '- 20 / - 4', 8999.0, '1 Year Warranty Only For Coating Peel Off', 'NO'),
('SV-10', 'Bonthus Blu Screen', 'single_vision', 'polycarbonate', '1.59', '- 8 / - 2 , - 6 / - 4   &  + 3 / + 1', 1499.0, '6 Months Warranty Only For Coating Peel Off', 'NO'),
('SV-11', 'Bonthus Blu +', 'single_vision', 'polycarbonate', '1.59', '- 8 / - 2 , - 6 / - 4   &  + 3 / + 1', 2499.0, '6 Months Warranty Only For Coating Peel Off', 'NO'),
('SV-12', 'Bonthus Night Driving', 'single_vision', 'polycarbonate', '1.59', '- 8 / - 2 , - 6 / - 4   &  + 3 / + 1', 3499.0, '1 Year Warranty Only For Coating Peel Off', 'NO'),
('PROG-1', 'Anti-Glare Normal Corridor', 'progressive', 'standard', '1.56', 'S + 8 to - 8 / C +4 to - 4', 1999.0, 'NO', 'NO'),
('PROG-2', 'Blu Noraml Corridor', 'progressive', 'standard', '1.56', 'S + 8 to - 8 / C +4 to - 5', 2999.0, '6 Months Warranty Only For Coating Peel Off', 'NO'),
('PROG-3', 'Wide Corridor', 'progressive', 'standard', '1.56', 'S + 8 to - 8 / C +4 to - 6', 5999.0, '6 Months Warranty Only For Coating Peel Off', 'JS'),
('PROG-4', 'Wide Corridor', 'progressive', 'standard', '1.67', 'S + 10 to - 15 / C + 4 to -4', 8499.0, '6 Months Warranty Only For Coating Peel Off', 'JS'),
('PROG-5', 'Wider Corridor', 'progressive', 'standard', '1.56', 'S + 8 to - 8 / C +4 to - 6', 9999.0, '1 Year Warranty Only For Coating Peel Off', 'BS'),
('PROG-8', 'Wider Corridor', 'progressive', 'standard', '1.67', 'S + 8 to - 8 / C +4 to - 6', 11999.0, '1 Year Warranty Only For Coating Peel Off', 'BS'),
('PROG-8', 'Wide Thin', 'progressive', 'standard', '1.74', 'S + 10 to - 20 / C + 4 to -4', 14999.0, '1 Year Warranty Only For Coating Peel Off', 'JS'),
('PROG-9', 'Wider Thin', 'progressive', 'standard', '1.74', 'S + 10 to - 20 / C + 4 to -4', 17999.0, '1 Year Warranty Only For Coating Peel Off', 'BS'),
('PROG-10', 'Blu Noraml Corridor', 'progressive', 'polycarbonate', '1.59', 'S +7 / - 8 / C + 4 - 4', 3499.0, '6 Months Warranty Only For Coating Peel Off', 'NO'),
('PROG-11', 'Wide Corridor', 'progressive', 'polycarbonate', '1.59', 'S +7 / - 8 / C + 4 - 4', 7999.0, '6 Months Warranty Only For Coating Peel Off', 'JS'),
('PROG-12', 'Wider Corridor', 'progressive', 'polycarbonate', '1.59', 'S +7 / - 8 / C + 4 - 4', 11999.0, '1 Year Warranty Only For Coating Peel Off', 'BS'),
('BI-1', 'No Coating', 'bifocal', 'standard', '1.56', 'S + 8 / - 8 to C + 4 / - 4', 999.0, 'NO', 'NO'),
('BI-2', 'Blu Screen', 'bifocal', 'standard', '1.56', 'S + 8 / - 8 to C + 4 / - 4', 2499.0, '6 Months Warranty Only For Coating Peel Off', 'NO'),
('BI-3', 'Poly Carbonate', 'bifocal', 'polycarbonate', '1.59', 'S + 8 / - 8 to C + 4 / - 4', 3499.0, '1 Year Warranty Only For Coating Peel Off', 'NO'),
('PHOTO-1', 'Photochromatic Coating Tier 1', 'photochromatic', 'standard', '', '', 600.0, 'NO Warranty', 'NO'),
('PHOTO-2', 'Photochromatic Coating Tier 2', 'photochromatic', 'standard', '', '', 800.0, 'NO Warranty', 'NO'),
('PHOTO-3', 'Photochromatic Coating Tier 3', 'photochromatic', 'standard', '', '', 1000.0, 'NO Warranty', 'NO'),
('PHOTO-4', 'Photochromatic Coating Tier 4', 'photochromatic', 'standard', '', '', 1200.0, 'NO Warranty', 'NO'),
('PHOTO-5', 'Photochromatic Coating Tier 5', 'photochromatic', 'standard', '', '', 1500.0, 'NO Warranty', 'NO'),
('PHOTO-6', 'Photochromatic Coating Tier 6', 'photochromatic', 'standard', '', '', 2000.0, 'NO Warranty', 'NO'),
('PHOTO-7', 'Photochromatic Coating Tier 7', 'photochromatic', 'standard', '', '', 2500.0, 'NO Warranty', 'NO'),
('PHOTO-8', 'Photochromatic Coating Tier 8', 'photochromatic', 'standard', '', '', 3000.0, 'NO Warranty', 'NO'),
('PHOTO-9', 'Photochromatic Coating Tier 9', 'photochromatic', 'standard', '', '', 3500.0, 'NO Warranty', 'NO');
